version: "3.9"

services:
  users.api:
    build:
      context: ./ProjectS.UsersService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: Users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
  
  redis:
    image: redis:latest
    container_name: projects_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - projects_redis_data:/data

  postgres:
    image: postgres:16
    container_name: users_postgres
    restart: always
    environment:
      POSTGRES_DB: Users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  projects_redis_data:
  postgres_data: